-- Create the necessary tables --
CREATE TABLE [IF NOT EXISTS] APPROVED_USERS (
    ID INT PRIMARY KEY NOT NULL,
    USERNAME TEXT NOT NULL
);

CREATE TABLE [IF NOT EXISTS] POSTS (
    ID INT PRIMARY KEY NOT NULL,
    POST_NAME TEXT UNIQUE,
    LINK TEXT NOT NULL,
    PRIMARY KEY (POST_NAME)
);

-- Load data for approved users. Formerly moderators, this will soon be anybody deemed cool --
INSERT INTO APPROVED_USERS (USERNAME) VALUES
    ('iTuna#0209'),
    ('Carissa#0420'),
    ('hugs#2593'),
    ('ash#0666'),
    ('LavenderGrooms#8008'),
    ('Tupperward#5115'),
    ('Jackapedia#1612');

-- Load data for all the memes --
INSERT INTO POSTS (POST_NAME, LINK) VALUES
    ('goodparenting', 'https://ibb.co/9c2Nj9c'),
    ('sixtynine', 'https://imgur.com/a/4qIriF2'),
    ('ass', 'https://imgur.com/a/qkAB9tM'),
    ('butterbean', 'https://imgur.com/a/n5M5co9'),
    ('didideath', 'https://imgur.com/a/Narr9EX'),
    ('elidelete', 'https://imgur.com/a/Lwbt1cW'),
    ('elismoltz', 'https://imgur.com/a/Lwbt1cW'),
    ('elistorm', 'https://imgur.com/a/gAPWP0t'),
    ('elitoilet', 'https://imgur.com/a/0T5OC3I'),
    ('clamshero', 'https://imgur.com/a/mlYLKKa'),
    ('kathfeet', 'https://imgur.com/a/pEeHwfh'),
    ('mmhbot', 'https://imgur.com/a/Hcjhwne'),
    ('backnine', 'https://imgur.com/a/FiCjgGS'),
    ('smoltzmojo', 'https://imgur.com/a/KVLMtMv'),
    ('stevefuck', 'https://imgur.com/a/El3vK4r'),
    ('stevestab', 'https://imgur.com/a/P2JvBjP'),
    ('smoltzstupid', 'https://imgur.com/a/5kKqOXH'),
    ('thegirlreadingth', 'https://imgur.com/OKjMqx2'),
    ('tweets', 'https://twitter.com/JungleClams/status/1136709154741997568?s=20'),
    ('tuppdoc', 'https://imgur.com/a/dL9xH7z'),
    ('wattba', 'https://imgur.com/a/6dljGKC'),
    ('smoltzchest', 'https://imgur.com/a/LrNpKL3'),
    ('dongbong', 'https://imgur.com/a/giJFsdW'),
    ('moonpie', 'https://imgur.com/a/39lnoeP'),
    ('smoltzrise', 'https://imgur.com/a/jv48kzq'),
    ('banner', 'https://imgur.com/a/uyPzkzR'),
    ('knockout', 'https://imgur.com/a/L7FIYPZ'),
    ('beanos', 'https://imgur.com/a/KRopvrH'),
    ('rip', 'https://imgur.com/a/gJXq0oF'),
    ('owned', 'https://imgur.com/tcEbsjq'),
    ('cumwars', 'https://imgur.com/5Oj8nm9'),
    ('buechsreaction', 'https://imgur.com/W0jhDmz'),
    ('yeaboi', 'https://imgur.com/OehgFA5'),
    ('willieroll', 'https://imgur.com/efF4klJ'),
    ('blood', 'https://imgur.com/Vwix320'),
    ('stuffed', 'https://imgur.com/3cn6quC'),
    ('potw', 'https://imgur.com/fKR8WKI'),
    ('hooboy', 'https://imgur.com/ifuncRl'),
    ('tarot', '!tarot'),
    ('shenyun', 'https://imgur.com/brN1hLP'),
    ('angery', 'https://imgur.com/OG09tqt'),
    ('nice','https://imgur.com/b2Uzbau'),
    ('picture','https://imgur.com/a/xIskr14'),
    ('wetthighs', 'https://imgur.com/XVdteLs'),
    ('tucker','https://youtu.be/GLqIB0h1vwY'),
    ('mindblown', 'https://imgur.com/BCN7kCQ'),
    ('yes', 'https://imgur.com/yRqIs7q'),
    ('grittyyes', 'https://imgur.com/v5MwA33'),
    ('batromance', 'https://youtu.be/7ZgdEnS4tdo'),
    ('jimmy', 'https://youtu.be/Q0hr8X2a2cc'),
    ('corybooker', 'https://imgur.com/lxWOokW'),
    ('gavel','https://imgur.com/a/M0YjjUT'),
    ('nutmonth', 'https://imgur.com/O8RRjIJ'),
    ('fuckduke', 'https://imgur.com/r70p4rB'),
    ('mildinconvenience', 'https://imgur.com/QU0lu0Q'),
    ('sip', 'https://imgur.com/L8X4Pef'),
    ('ham', 'https://imgur.com/iBr4xsb'),
    ('yike', 'https://imgur.com/CxujlYQ'),
    ('boomerass', 'https://imgur.com/1btK9uI'),
    ('hornypatrol', 'https://imgur.com/JwPNrRI'),
    ('random', 'Heathcliff random random comment'),
    ('onething', 'https://www.youtube.com/watch?v=1Q-U2THOF00'),
    ('hpu', 'https://imgur.com/062ammM'),
    ('girls', 'https://imgur.com/vjrgb3F'),
    ('fists', 'https://imgur.com/vMMOe7E'),
    ('papabless', 'https://imgur.com/SBqqHuX'),
    ('homeboy','https://imgur.com/a/WZBqWEP)'),
    ('report','https://imgur.com/a/1V3XUgP)'),
    ('gamers', 'https://imgur.com/BMWS0sh'),
    ('borb', 'https://imgur.com/aV3FWcu'),
    ('phatt', 'https://imgur.com/8GJbZZX'),
    ('glad', 'https://imgur.com/ERArFac'),
    ('cybersteve', 'https://imgur.com/Tsc6CGi'),
    ('yesfecta', 'https://imgur.com/hE2sk0k'),
    ('marianne', 'https://imgur.com/8nrgiKg'),
    ('chachapost','https://imgur.com/a/bQPRJd8'),
    ('bullshit','https://imgur.com/a/inlvP4e'),
    ('jeff', 'https://imgur.com/Nt3WooR'),
    ('cbt', 'https://imgur.com/rL4DgNc'),
    ('chuck', 'https://imgur.com/OoEAfgn'),
    ('oops', 'https://imgur.com/0qrkudt'),
    ('duality', 'https://imgur.com/SODqLvi'),
    ('thiccthunk', 'https://i.boring.host/1153cNgf.png'),
    ('tunamorning', 'https://imgur.com/a/dtzLGDy'),
    ('blowout', 'https://imgur.com/A4VxLjc'),
    ('fridaynight', 'https://twitter.com/cat_beltane/status/1123424177023746049'),
    ('turdthoughts', 'https://imgur.com/yJWsuQb'),
    ('mods', 'https://imgur.com/LRV6mQX'),
    ('doodoo', 'https://imgur.com/ZluUra3'),
    ('fight', 'https://imgur.com/Kq9Tw85'),
    ('thisdiscord', 'https://imgur.com/xeciLwq'),
    ('politics', 'https://imgur.com/i9V802Q'),
    ('throwup', 'https://imgur.com/UXid6Vc'),
    ('fetlife', 'https://imgur.com/OLGzBYD'),
    ('disgust', 'https://imgur.com/zyLiEaP'),
    ('riakkuma', 'https://imgur.com/oUh4RFk'),
    ('coolthink', 'https://imgur.com/dXi1Q9u'),
    ('pigs', 'https://imgur.com/PdfA1Lc'),
    ('get', 'https://pbs.twimg.com/media/EAaD2pGWkAAm3bC?format=jpg&name=small'),
    ('blocktuna', 'https://imgur.com/dW654Mq'),
    ('crab','https://imgur.com/SP9JLxk'),
    ('praxis','https://imgur.com/1d2UNhS'),
    ('kofie','https://imgur.com/TyBAw4M'),
    ('unpack','https://imgur.com/12ZqKBN'),
    ('stephen','https://imgur.com/oszDPNY'),
    ('italian','https://imgur.com/WlFzkmf'),
    ('homer','https://imgur.com/Rba6HlS'),
    ('bb','https://imgur.com/14Zi9FW'),
    ('wish','https://imgur.com/tDLMxut'),
    ('silencecrab','https://imgur.com/XJsM2GV'),
    ('overkill','https://imgur.com/uxF2r9Z'),
    ('brad','https://imgur.com/TRFz6xD'),
    ('dragula','https://youtu.be/EqQuihD0hoI'),
    ('tuppnut','https://imgur.com/e7IMlZp'),
    ('empathy','https://imgur.com/xB9Os9k'),
    ('matty','https://imgur.com/SZSNjYm'),
    ('pete', 'https://youtu.be/5-UrFiz3nwI'),
    ('beep', 'meatball'),
    ('meatball','https://imgur.com/2USGlDq'),
    ('beephole','https://imgur.com/Kuu4PJP'),
    ('pee','https://imgur.com/O2LYrAr'),
    ('newhobby','https://imgur.com/a/NF5ABXc'),
    ('columbo','https://imgur.com/a/I7dYt52'),
    ('yang', 'https://youtu.be/K1jUJ-2MsdA'),
    ('awesomeface', 'https://media.tenor.com/images/55ce2e51387e26d301c4a51f1f01ce9d/tenor.gif'),
    ('wasntfinished', 'https://imgur.com/v6hNlov'),
    ('godiva', 'https://twitter.com/nickciarelli/status/1087412135066427392'),
    ('subway', 'https://imgur.com/FVzfHj9'),
    ('wolf', 'https://imgur.com/w46nLQj'),
    ('contempt', 'https://imgur.com/jIdQrLS'),
    ('khive', 'https://redd.it/a8arw9dvqrs21.jpg'),
    ('mikeface', 'https://imgur.com/wvPBcck'),
    ('cretins', 'https://imgur.com/a/WYxRYB8'),
    ('bglobby', 'https://imgur.com/a/XiFewQv'),
    ('8', 'https://tenor.com/view/star-wars-bb8-rollin-gif-4826503'),
    ('salami', 'https://imgur.com/z5yxcyG'),
    ('tear', 'https://imgur.com/Uqdumz6'),
    ('bed', 'https://imgur.com/0yR3pbv'),
    ('liam', 'https://tenor.com/3Yxn.gif'),
    ('impact', 'https://imgur.com/DfqEIxz'),
    ('football', 'https://imgur.com/Y0JmP69'),
    ('defeat', 'https://imgur.com/cUMdhMH'),
    ('rat', 'https://imgur.com/LSjNpnD'),
    ('eyes', 'https://imgur.com/WJGprMp'),
    ('pizzarat', 'https://imgur.com/TMHRcrA'),
    ('mixed', 'https://imgur.com/OanECEO'),
    ('optimus', 'https://imgur.com/xI9yt48.gif'),
    ('squad', 'https://imgur.com/SxsO6Se'),
    ('board', 'https://imgur.com/9yiRJyA'),
    ('slamders', 'https://imgur.com/nqgD3OB'),
    ('localman', 'https://imgur.com/VcsSTk7'),
    ('garflush', 'https://imgur.com/On709gu'),
    ('smug', 'https://imgur.com/ctlwJ3s'),
    ('tommyleejones', 'https://imgur.com/VfUXoDl'),
    ('joker', 'https://imgur.com/B2Wuu8U'),
    ('bad', 'https://imgur.com/VFaDAE8'),
    ('gd', 'https://imgur.com/EkwPJ0G'),
    ('baby', 'https://imgur.com/IzB1eL9'),
    ('dodged', 'https://imgur.com/oqaR6CJ'),
    ('guess', 'https://imgur.com/dbCYuox'),
    ('stevethumb', 'https://imgur.com/TW18TaL'),
    ('antigd', 'https://imgur.com/kk4jVLp'),
    ('hogwarts', 'https://imgur.com/a/sYh7n93'),
    ('garfield', 'https://imgur.com/lCqcLrR'),
    ('order', 'https://imgur.com/BGR8Zmi'),
    ('spray', 'https://imgur.com/OUOAar7'),
    ('theacuck', 'https://imgur.com/Qc6KjLG'),
    ('gorbage', 'https://imgur.com/HNISraI'),
    ('pattyvoice', 'https://imgur.com/AZlzEUo'),
    ('nuclearoption', 'https://imgur.com/ZBm2xHo'),
    ('uber', 'https://twitter.com/robwhisman/status/735281634656669696'),
    ('gamers2', 'https://imgur.com/KN9vVyu'),
    ('miamad', 'https://imgur.com/6NPL4nJ'),
    ('partyvoice', 'https://imgur.com/JUIW2gv'),
    ('starfish', 'https://imgur.com/lT7113p'),
    ('lisavoice', 'https://imgur.com/lCpXr6y'),
    ('tuppsmell', 'https://imgur.com/QhbbgVi'),
    ('cumdad', 'https://imgur.com/GQ9aAXB'),
    ('bab', 'https://imgur.com/E4bukZr'),
    ('jack', 'https://imgur.com/E4bukZr'),
    ('teefhtak', 'https://imgur.com/8fVQo02'),
    ('puzzle', 'https://imgur.com/wkMootm'),
    ('cube', 'https://imgur.com/UDlf6TS'),
    ('when'	, 'https://imgur.com/a/GttXOmT'),
    ('jackplug', 'https://www.jackapedia.design/'),
    ('idolcon',	'https://www.theidolcon.com/'),
    ('steveplug', 'https://stephenalcala.com/'),
    ('lmm', 'https://imgur.com/v654Jf8'),
    ('guy', 'https://imgur.com/Jg3VUoE'),
    ('dudestop', 'https://imgur.com/AuJgWL3'),
    ('a+', 'https//imgur.com/W1cdjmu'),
    ('yupp', 'https://imgur.com/ffuYCMY'),
    ('yeababy', 'https://imgur.com/Ry5hbNI'),
    ('contempt', 'https://imgur.com/w4pliwq'),
    ('pedal', 'https://imgur.com/8YLHzm8'),
    ('contentment', 'https://imgur.com/yUq2QCk'),
    ('smackwetz', 'https://imgur.com/vN3Z5zt'),
    ('miapiss', 'https://imgur.com/KdEAFNq');


