PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Approved_Users (ID INT PRIMARY KEY, username TEXT );
INSERT INTO Approved_Users VALUES(NULL,'iTuna#0209');
INSERT INTO Approved_Users VALUES(NULL,'Carissa#0420');
INSERT INTO Approved_Users VALUES(NULL,'hugs#2593');
INSERT INTO Approved_Users VALUES(NULL,'ash#0666');
INSERT INTO Approved_Users VALUES(NULL,'LavenderGrooms#8008');
INSERT INTO Approved_Users VALUES(NULL,'Tupperward#5115');
INSERT INTO Approved_Users VALUES(NULL,'Jackapedia#1612');
CREATE TABLE Posts (ID INT PRIMARY KEY, post_name TEXT, link TEXT);
INSERT INTO Posts VALUES(NULL,'goodparenting','https://ibb.co/9c2Nj9c');
INSERT INTO Posts VALUES(NULL,'sixtynine','https://imgur.com/a/4qIriF2');
INSERT INTO Posts VALUES(NULL,'ass','https://imgur.com/a/qkAB9tM');
INSERT INTO Posts VALUES(NULL,'butterbean','https://imgur.com/a/n5M5co9');
INSERT INTO Posts VALUES(NULL,'didideath','https://imgur.com/a/Narr9EX');
INSERT INTO Posts VALUES(NULL,'elidelete','https://imgur.com/a/Lwbt1cW');
INSERT INTO Posts VALUES(NULL,'elismoltz','https://imgur.com/a/Lwbt1cW');
INSERT INTO Posts VALUES(NULL,'elistorm','https://imgur.com/a/gAPWP0t');
INSERT INTO Posts VALUES(NULL,'elitoilet','https://imgur.com/a/0T5OC3I');
INSERT INTO Posts VALUES(NULL,'clamshero','https://imgur.com/a/mlYLKKa');
INSERT INTO Posts VALUES(NULL,'kathfeet','https://imgur.com/a/pEeHwfh');
INSERT INTO Posts VALUES(NULL,'mmhbot','https://imgur.com/a/Hcjhwne');
INSERT INTO Posts VALUES(NULL,'backnine','https://imgur.com/a/FiCjgGS');
INSERT INTO Posts VALUES(NULL,'smoltzmojo','https://imgur.com/a/KVLMtMv');
INSERT INTO Posts VALUES(NULL,'stevefuck','https://imgur.com/a/El3vK4r');
INSERT INTO Posts VALUES(NULL,'stevestab','https://imgur.com/a/P2JvBjP');
INSERT INTO Posts VALUES(NULL,'smoltzstupid','https://imgur.com/a/5kKqOXH');
INSERT INTO Posts VALUES(NULL,'thegirlreadingth','https://imgur.com/OKjMqx2');
INSERT INTO Posts VALUES(NULL,'tweets','https://twitter.com/JungleClams/status/1136709154741997568?s=20');
INSERT INTO Posts VALUES(NULL,'tuppdoc','https://imgur.com/a/dL9xH7z');
INSERT INTO Posts VALUES(NULL,'wattba','https://imgur.com/a/6dljGKC');
INSERT INTO Posts VALUES(NULL,'smoltzchest','https://imgur.com/a/LrNpKL3');
INSERT INTO Posts VALUES(NULL,'dongbong','https://imgur.com/a/giJFsdW');
INSERT INTO Posts VALUES(NULL,'moonpie','https://imgur.com/a/39lnoeP');
INSERT INTO Posts VALUES(NULL,'smoltzrise','https://imgur.com/a/jv48kzq');
INSERT INTO Posts VALUES(NULL,'banner','https://imgur.com/a/uyPzkzR');
INSERT INTO Posts VALUES(NULL,'knockout','https://imgur.com/a/L7FIYPZ');
INSERT INTO Posts VALUES(NULL,'beanos','https://imgur.com/a/KRopvrH');
INSERT INTO Posts VALUES(NULL,'rip','https://imgur.com/a/gJXq0oF');
INSERT INTO Posts VALUES(NULL,'owned','https://imgur.com/tcEbsjq');
INSERT INTO Posts VALUES(NULL,'cumwars','https://imgur.com/5Oj8nm9');
INSERT INTO Posts VALUES(NULL,'buechsreaction','https://imgur.com/W0jhDmz');
INSERT INTO Posts VALUES(NULL,'yeaboi','https://imgur.com/OehgFA5');
INSERT INTO Posts VALUES(NULL,'willieroll','https://imgur.com/efF4klJ');
INSERT INTO Posts VALUES(NULL,'blood','https://imgur.com/Vwix320');
INSERT INTO Posts VALUES(NULL,'stuffed','https://imgur.com/3cn6quC');
INSERT INTO Posts VALUES(NULL,'potw','https://imgur.com/fKR8WKI');
INSERT INTO Posts VALUES(NULL,'hooboy','https://imgur.com/ifuncRl');
INSERT INTO Posts VALUES(NULL,'tarot','!tarot');
INSERT INTO Posts VALUES(NULL,'shenyun','https://imgur.com/brN1hLP');
INSERT INTO Posts VALUES(NULL,'angery','https://imgur.com/OG09tqt');
INSERT INTO Posts VALUES(NULL,'nice','https://imgur.com/b2Uzbau');
INSERT INTO Posts VALUES(NULL,'picture','https://imgur.com/a/xIskr14');
INSERT INTO Posts VALUES(NULL,'wetthighs','https://imgur.com/XVdteLs');
INSERT INTO Posts VALUES(NULL,'tucker','https://youtu.be/GLqIB0h1vwY');
INSERT INTO Posts VALUES(NULL,'mindblown','https://imgur.com/BCN7kCQ');
INSERT INTO Posts VALUES(NULL,'yes','https://imgur.com/yRqIs7q');
INSERT INTO Posts VALUES(NULL,'grittyyes','https://imgur.com/v5MwA33');
INSERT INTO Posts VALUES(NULL,'batromance','https://youtu.be/7ZgdEnS4tdo');
INSERT INTO Posts VALUES(NULL,'jimmy','https://youtu.be/Q0hr8X2a2cc');
INSERT INTO Posts VALUES(NULL,'corybooker','https://imgur.com/lxWOokW');
INSERT INTO Posts VALUES(NULL,'gavel','https://imgur.com/a/M0YjjUT');
INSERT INTO Posts VALUES(NULL,'nutmonth','https://imgur.com/O8RRjIJ');
INSERT INTO Posts VALUES(NULL,'fuckduke','https://imgur.com/r70p4rB');
INSERT INTO Posts VALUES(NULL,'mildinconvenience','https://imgur.com/QU0lu0Q');
INSERT INTO Posts VALUES(NULL,'sip','https://imgur.com/L8X4Pef');
INSERT INTO Posts VALUES(NULL,'ham','https://imgur.com/iBr4xsb');
INSERT INTO Posts VALUES(NULL,'yike','https://imgur.com/CxujlYQ');
INSERT INTO Posts VALUES(NULL,'boomerass','https://imgur.com/1btK9uI');
INSERT INTO Posts VALUES(NULL,'hornypatrol','https://imgur.com/JwPNrRI');
INSERT INTO Posts VALUES(NULL,'random','Heathcliff random random comment');
INSERT INTO Posts VALUES(NULL,'onething','https://www.youtube.com/watch?v=1Q-U2THOF00');
INSERT INTO Posts VALUES(NULL,'hpu','https://imgur.com/062ammM');
INSERT INTO Posts VALUES(NULL,'girls','https://imgur.com/vjrgb3F');
INSERT INTO Posts VALUES(NULL,'fists','https://imgur.com/vMMOe7E');
INSERT INTO Posts VALUES(NULL,'papabless','https://imgur.com/SBqqHuX');
INSERT INTO Posts VALUES(NULL,'homeboy','https://imgur.com/a/WZBqWEP)');
INSERT INTO Posts VALUES(NULL,'report','https://imgur.com/a/1V3XUgP)');
INSERT INTO Posts VALUES(NULL,'gamers','https://imgur.com/BMWS0sh');
INSERT INTO Posts VALUES(NULL,'borb','https://imgur.com/aV3FWcu');
INSERT INTO Posts VALUES(NULL,'phatt','https://imgur.com/8GJbZZX');
INSERT INTO Posts VALUES(NULL,'glad','https://imgur.com/ERArFac');
INSERT INTO Posts VALUES(NULL,'cybersteve','https://imgur.com/Tsc6CGi');
INSERT INTO Posts VALUES(NULL,'yesfecta','https://imgur.com/hE2sk0k');
INSERT INTO Posts VALUES(NULL,'marianne','https://imgur.com/8nrgiKg');
INSERT INTO Posts VALUES(NULL,'chachapost','https://imgur.com/a/bQPRJd8');
INSERT INTO Posts VALUES(NULL,'bullshit','https://imgur.com/a/inlvP4e');
INSERT INTO Posts VALUES(NULL,'jeff','https://imgur.com/Nt3WooR');
INSERT INTO Posts VALUES(NULL,'cbt','https://imgur.com/rL4DgNc');
INSERT INTO Posts VALUES(NULL,'chuck','https://imgur.com/OoEAfgn');
INSERT INTO Posts VALUES(NULL,'oops','https://imgur.com/0qrkudt');
INSERT INTO Posts VALUES(NULL,'duality','https://imgur.com/SODqLvi');
INSERT INTO Posts VALUES(NULL,'thiccthunk','https://i.boring.host/1153cNgf.png');
INSERT INTO Posts VALUES(NULL,'tunamorning','https://imgur.com/a/dtzLGDy');
INSERT INTO Posts VALUES(NULL,'blowout','https://imgur.com/A4VxLjc');
INSERT INTO Posts VALUES(NULL,'fridaynight','https://twitter.com/cat_beltane/status/1123424177023746049');
INSERT INTO Posts VALUES(NULL,'turdthoughts','https://imgur.com/yJWsuQb');
INSERT INTO Posts VALUES(NULL,'mods','https://imgur.com/LRV6mQX');
INSERT INTO Posts VALUES(NULL,'doodoo','https://imgur.com/ZluUra3');
INSERT INTO Posts VALUES(NULL,'fight','https://imgur.com/Kq9Tw85');
INSERT INTO Posts VALUES(NULL,'thisdiscord','https://imgur.com/xeciLwq');
INSERT INTO Posts VALUES(NULL,'politics','https://imgur.com/i9V802Q');
INSERT INTO Posts VALUES(NULL,'throwup','https://imgur.com/UXid6Vc');
INSERT INTO Posts VALUES(NULL,'fetlife','https://imgur.com/OLGzBYD');
INSERT INTO Posts VALUES(NULL,'disgust','https://imgur.com/zyLiEaP');
INSERT INTO Posts VALUES(NULL,'riakkuma','https://imgur.com/oUh4RFk');
INSERT INTO Posts VALUES(NULL,'coolthink','https://imgur.com/dXi1Q9u');
INSERT INTO Posts VALUES(NULL,'pigs','https://imgur.com/PdfA1Lc');
INSERT INTO Posts VALUES(NULL,'get','https://pbs.twimg.com/media/EAaD2pGWkAAm3bC?format=jpg&name=small');
INSERT INTO Posts VALUES(NULL,'blocktuna','https://imgur.com/dW654Mq');
INSERT INTO Posts VALUES(NULL,'crab','https://imgur.com/SP9JLxk');
INSERT INTO Posts VALUES(NULL,'praxis','https://imgur.com/1d2UNhS');
INSERT INTO Posts VALUES(NULL,'kofie','https://imgur.com/TyBAw4M');
INSERT INTO Posts VALUES(NULL,'unpack','https://imgur.com/12ZqKBN');
INSERT INTO Posts VALUES(NULL,'stephen','https://imgur.com/oszDPNY');
INSERT INTO Posts VALUES(NULL,'italian','https://imgur.com/WlFzkmf');
INSERT INTO Posts VALUES(NULL,'homer','https://imgur.com/Rba6HlS');
INSERT INTO Posts VALUES(NULL,'bb','https://imgur.com/14Zi9FW');
INSERT INTO Posts VALUES(NULL,'wish','https://imgur.com/tDLMxut');
INSERT INTO Posts VALUES(NULL,'silencecrab','https://imgur.com/XJsM2GV');
INSERT INTO Posts VALUES(NULL,'overkill','https://imgur.com/uxF2r9Z');
INSERT INTO Posts VALUES(NULL,'brad','https://imgur.com/TRFz6xD');
INSERT INTO Posts VALUES(NULL,'dragula','https://youtu.be/EqQuihD0hoI');
INSERT INTO Posts VALUES(NULL,'tuppnut','https://imgur.com/e7IMlZp');
INSERT INTO Posts VALUES(NULL,'empathy','https://imgur.com/xB9Os9k');
INSERT INTO Posts VALUES(NULL,'matty','https://imgur.com/SZSNjYm');
INSERT INTO Posts VALUES(NULL,'pete','https://youtu.be/5-UrFiz3nwI');
INSERT INTO Posts VALUES(NULL,'beep','meatball');
INSERT INTO Posts VALUES(NULL,'meatball','https://imgur.com/2USGlDq');
INSERT INTO Posts VALUES(NULL,'beephole','https://imgur.com/Kuu4PJP');
INSERT INTO Posts VALUES(NULL,'pee','https://imgur.com/O2LYrAr');
INSERT INTO Posts VALUES(NULL,'newhobby','https://imgur.com/a/NF5ABXc');
INSERT INTO Posts VALUES(NULL,'columbo','https://imgur.com/a/I7dYt52');
INSERT INTO Posts VALUES(NULL,'yang','https://youtu.be/K1jUJ-2MsdA');
INSERT INTO Posts VALUES(NULL,'awesomeface','https://media.tenor.com/images/55ce2e51387e26d301c4a51f1f01ce9d/tenor.gif');
INSERT INTO Posts VALUES(NULL,'wasntfinished','https://imgur.com/v6hNlov');
INSERT INTO Posts VALUES(NULL,'godiva','https://twitter.com/nickciarelli/status/1087412135066427392');
INSERT INTO Posts VALUES(NULL,'subway','https://imgur.com/FVzfHj9');
INSERT INTO Posts VALUES(NULL,'wolf','https://imgur.com/w46nLQj');
INSERT INTO Posts VALUES(NULL,'contempt','https://imgur.com/jIdQrLS');
INSERT INTO Posts VALUES(NULL,'khive','https://redd.it/a8arw9dvqrs21.jpg');
INSERT INTO Posts VALUES(NULL,'mikeface','https://imgur.com/wvPBcck');
INSERT INTO Posts VALUES(NULL,'cretins','https://imgur.com/a/WYxRYB8');
INSERT INTO Posts VALUES(NULL,'bglobby','https://imgur.com/a/XiFewQv');
INSERT INTO Posts VALUES(NULL,'8','https://tenor.com/view/star-wars-bb8-rollin-gif-4826503');
INSERT INTO Posts VALUES(NULL,'salami','https://imgur.com/z5yxcyG');
INSERT INTO Posts VALUES(NULL,'tear','https://imgur.com/Uqdumz6');
INSERT INTO Posts VALUES(NULL,'bed','https://imgur.com/0yR3pbv');
INSERT INTO Posts VALUES(NULL,'liam','https://tenor.com/3Yxn.gif');
INSERT INTO Posts VALUES(NULL,'impact','https://imgur.com/DfqEIxz');
INSERT INTO Posts VALUES(NULL,'football','https://imgur.com/Y0JmP69');
INSERT INTO Posts VALUES(NULL,'defeat','https://imgur.com/cUMdhMH');
INSERT INTO Posts VALUES(NULL,'rat','https://imgur.com/LSjNpnD');
INSERT INTO Posts VALUES(NULL,'eyes','https://imgur.com/WJGprMp');
INSERT INTO Posts VALUES(NULL,'pizzarat','https://imgur.com/TMHRcrA');
INSERT INTO Posts VALUES(NULL,'mixed','https://imgur.com/OanECEO');
INSERT INTO Posts VALUES(NULL,'optimus','https://imgur.com/xI9yt48.gif');
INSERT INTO Posts VALUES(NULL,'squad','https://imgur.com/SxsO6Se');
INSERT INTO Posts VALUES(NULL,'board','https://imgur.com/9yiRJyA');
INSERT INTO Posts VALUES(NULL,'slamders','https://imgur.com/nqgD3OB');
INSERT INTO Posts VALUES(NULL,'localman','https://imgur.com/VcsSTk7');
INSERT INTO Posts VALUES(NULL,'garflush','https://imgur.com/On709gu');
INSERT INTO Posts VALUES(NULL,'smug','https://imgur.com/ctlwJ3s');
INSERT INTO Posts VALUES(NULL,'tommyleejones','https://imgur.com/VfUXoDl');
INSERT INTO Posts VALUES(NULL,'joker','https://imgur.com/B2Wuu8U');
INSERT INTO Posts VALUES(NULL,'bad','https://imgur.com/VFaDAE8');
INSERT INTO Posts VALUES(NULL,'gd','https://imgur.com/EkwPJ0G');
INSERT INTO Posts VALUES(NULL,'baby','https://imgur.com/IzB1eL9');
INSERT INTO Posts VALUES(NULL,'dodged','https://imgur.com/oqaR6CJ');
INSERT INTO Posts VALUES(NULL,'guess','https://imgur.com/dbCYuox');
INSERT INTO Posts VALUES(NULL,'stevethumb','https://imgur.com/TW18TaL');
INSERT INTO Posts VALUES(NULL,'antigd','https://imgur.com/kk4jVLp');
INSERT INTO Posts VALUES(NULL,'hogwarts','https://imgur.com/a/sYh7n93');
INSERT INTO Posts VALUES(NULL,'garfield','https://imgur.com/lCqcLrR');
INSERT INTO Posts VALUES(NULL,'order','https://imgur.com/BGR8Zmi');
INSERT INTO Posts VALUES(NULL,'spray','https://imgur.com/OUOAar7');
INSERT INTO Posts VALUES(NULL,'theacuck','https://imgur.com/Qc6KjLG');
INSERT INTO Posts VALUES(NULL,'gorbage','https://imgur.com/HNISraI');
INSERT INTO Posts VALUES(NULL,'pattyvoice','https://imgur.com/AZlzEUo');
INSERT INTO Posts VALUES(NULL,'nuclearoption','https://imgur.com/ZBm2xHo');
INSERT INTO Posts VALUES(NULL,'uber','https://twitter.com/robwhisman/status/735281634656669696');
INSERT INTO Posts VALUES(NULL,'gamers2','https://imgur.com/KN9vVyu');
INSERT INTO Posts VALUES(NULL,'miamad','https://imgur.com/6NPL4nJ');
INSERT INTO Posts VALUES(NULL,'partyvoice','https://imgur.com/JUIW2gv');
INSERT INTO Posts VALUES(NULL,'starfish','https://imgur.com/lT7113p');
INSERT INTO Posts VALUES(NULL,'lisavoice','https://imgur.com/lCpXr6y');
INSERT INTO Posts VALUES(NULL,'tuppsmell','https://imgur.com/QhbbgVi');
INSERT INTO Posts VALUES(NULL,'cumdad','https://imgur.com/GQ9aAXB');
INSERT INTO Posts VALUES(NULL,'bab','https://imgur.com/E4bukZr');
INSERT INTO Posts VALUES(NULL,'jack','https://imgur.com/E4bukZr');
INSERT INTO Posts VALUES(NULL,'teefhtak','https://imgur.com/8fVQo02');
INSERT INTO Posts VALUES(NULL,'puzzle','https://imgur.com/wkMootm');
INSERT INTO Posts VALUES(NULL,'cube','https://imgur.com/UDlf6TS');
INSERT INTO Posts VALUES(NULL,'when','https://imgur.com/a/GttXOmT');
INSERT INTO Posts VALUES(NULL,'jackplug','https://www.jackapedia.design/');
INSERT INTO Posts VALUES(NULL,'idolcon','https://www.theidolcon.com/');
INSERT INTO Posts VALUES(NULL,'steveplug','https://stephenalcala.com/');
INSERT INTO Posts VALUES(NULL,'lmm','https://imgur.com/v654Jf8');
INSERT INTO Posts VALUES(NULL,'guy','https://imgur.com/Jg3VUoE');
INSERT INTO Posts VALUES(NULL,'dudestop','https://imgur.com/AuJgWL3');
INSERT INTO Posts VALUES(NULL,'a+','https//imgur.com/W1cdjmu');
INSERT INTO Posts VALUES(NULL,'yupp','https://imgur.com/ffuYCMY');
INSERT INTO Posts VALUES(NULL,'yeababy','https://imgur.com/Ry5hbNI');
INSERT INTO Posts VALUES(NULL,'contempt','https://imgur.com/w4pliwq');
INSERT INTO Posts VALUES(NULL,'pedal','https://imgur.com/8YLHzm8');
INSERT INTO Posts VALUES(NULL,'contentment','https://imgur.com/yUq2QCk');
INSERT INTO Posts VALUES(NULL,'smackwetz','https://imgur.com/vN3Z5zt');
INSERT INTO Posts VALUES(NULL,'miapiss','https://imgur.com/KdEAFNq');
CREATE TABLE IF NOT EXISTS "bobQuotes" (
	id INTEGER NOT NULL, 
	quote VARCHAR, 
	PRIMARY KEY (id)
);
INSERT INTO bobQuotes VALUES(1,'There’s nothing wrong with having a tree as a friend.');
INSERT INTO bobQuotes VALUES(2,'The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe.');
INSERT INTO bobQuotes VALUES(3,'We don’t make mistakes. We just have happy accidents.');
INSERT INTO bobQuotes VALUES(4,'I think there’s an artist hidden at the bottom of every single one of us.');
INSERT INTO bobQuotes VALUES(5,'You too can paint almighty pictures.');
INSERT INTO bobQuotes VALUES(6,'No pressure. Just relax and watch it happen.');
INSERT INTO bobQuotes VALUES(7,'Don’t forget to make all these little things individuals — all of them special in their own way.');
INSERT INTO bobQuotes VALUES(8,'Find freedom on this canvas.');
INSERT INTO bobQuotes VALUES(9,'It’s so important to do something every day that will make you happy.');
INSERT INTO bobQuotes VALUES(10,'Talent is a pursued interest. Anything that you’re willing to practice, you can do.');
INSERT INTO bobQuotes VALUES(11,'Make love to the canvas.');
INSERT INTO bobQuotes VALUES(12,'[Painting] will bring a lot of good thoughts to your heart.');
INSERT INTO bobQuotes VALUES(13,'We artists are a different breed of people. We’re a happy bunch.');
INSERT INTO bobQuotes VALUES(14,'We want happy paintings. Happy paintings. If you want sad things, watch the news.');
INSERT INTO bobQuotes VALUES(15,'That’s a crooked tree. We’ll send him to Washington.');
INSERT INTO bobQuotes VALUES(16,'Every day is a good day when you paint.');
INSERT INTO bobQuotes VALUES(17,'I think each of us, sometime in our life, has wanted to paint a picture.');
INSERT INTO bobQuotes VALUES(18,'We tell people sometimes: We’re like drug dealers, come into town and get everybody absolutely addicted to painting. It doesn’t take much to get you addicted.');
INSERT INTO bobQuotes VALUES(19,'They say everything looks better with odd numbers of things. But sometimes I put even numbers — just to upset the critics.');
INSERT INTO bobQuotes VALUES(20,'Gotta give him a friend. Like I always say, ‘Everyone needs a friend.’');
INSERT INTO bobQuotes VALUES(21,'See how it fades right into nothing. That’s just what you’re looking for.');
INSERT INTO bobQuotes VALUES(22,'If I paint something, I don’t want to have to explain what it is.');
INSERT INTO bobQuotes VALUES(23,'Water’s like me. It’s lazy. Boy, it always looks for the easiest way to do things.');
INSERT INTO bobQuotes VALUES(24,'In painting, you have unlimited power. You have the ability to move mountains. You can bend rivers. But when I get home, the only thing I have power over is the garbage.');
INSERT INTO bobQuotes VALUES(25,'Don’t forget to tell these special people in your life just how special they are to you.');
INSERT INTO bobQuotes VALUES(26,'Didn’t you know you had that much power? You can move mountains. You can do anything.');
INSERT INTO bobQuotes VALUES(27,'I like to beat the brush.');
INSERT INTO bobQuotes VALUES(28,'Just let go — and fall like a little waterfall.');
INSERT INTO bobQuotes VALUES(29,'Talk to the tree, make friends with it.');
INSERT INTO bobQuotes VALUES(30,'I taught my son to paint mountains like these, and guess what? Now he paints the best darn mountains in the industry.');
INSERT INTO bobQuotes VALUES(31,'I really believe that if you practice enough you could paint the ‘Mona Lisa’ with a two-inch brush.');
INSERT INTO bobQuotes VALUES(32,'Be so very light. Be a gentle whisper.');
INSERT INTO bobQuotes VALUES(33,'Use absolutely no pressure. Just like an angel’s wing.');
INSERT INTO bobQuotes VALUES(34,'You need the dark in order to show the light.');
INSERT INTO bobQuotes VALUES(35,'You can do anything you want to do. This is your world.');
INSERT INTO bobQuotes VALUES(36,'You have to allow the paint to break to make it beautiful.');
INSERT INTO bobQuotes VALUES(37,'However you think it should be, that’s exactly how it should be.');
INSERT INTO bobQuotes VALUES(38,'In nature, dead trees are just as normal as live trees.');
INSERT INTO bobQuotes VALUES(39,'You can have anything you want in the world — once you help everyone around you get what they want.');
INSERT INTO bobQuotes VALUES(40,'If you do too much, it’s going to lose its effectiveness.');
INSERT INTO bobQuotes VALUES(41,'This is happy place; little squirrels live here and play.');
INSERT INTO bobQuotes VALUES(42,'That’s where the crows will sit. But we’ll have to put an elevator to put them up there because they can’t fly, but they don’t know that, so they still try.');
INSERT INTO bobQuotes VALUES(43,'Remember how free clouds are. They just lay around in the sky all day long.');
INSERT INTO bobQuotes VALUES(44,'We don’t really know where this goes — and I’m not sure we really care.');
INSERT INTO bobQuotes VALUES(45,'If we’re going to have animals around we all have to be concerned about them and take care of them.');
INSERT INTO bobQuotes VALUES(46,'You can do anything here — the only prerequisite is that it makes you happy.');
INSERT INTO bobQuotes VALUES(47,'Go out on a limb — that’s where the fruit is.');
INSERT INTO bobQuotes VALUES(48,'Isn’t it fantastic that you can change your mind and create all these happy things?');
INSERT INTO bobQuotes VALUES(49,'Anytime you learn, you gain.');
INSERT INTO bobQuotes VALUES(50,'It’s life. It’s interesting. It’s fun.');
INSERT INTO bobQuotes VALUES(51,'Trees are like people. They all have a few flaws in them.');
INSERT INTO bobQuotes VALUES(52,'When you get a little challenge in your life you tend to enjoy it.');
INSERT INTO bobQuotes VALUES(53,'Even a little tree will grow up to be a big tree. All it needs is water, sunshine and love - the same as all of us.');
INSERT INTO bobQuotes VALUES(54,'There’s tranquility and peace in my world, there’s never any violence.');
INSERT INTO bobQuotes VALUES(55,'Art should make you feel good about yourself and about the world.');
INSERT INTO bobQuotes VALUES(56,'It is my world and everything in my world is happy.');
INSERT INTO bobQuotes VALUES(57,'If it ain’t broke, don’t fix it - but nothing is broken, so don’t worry about trying to fix anything.');
INSERT INTO bobQuotes VALUES(58,'Let’s be brave - because we can do anything.');
INSERT INTO bobQuotes VALUES(59,'We all have different ideas - and they’re all good - there is no good or bad.');
INSERT INTO bobQuotes VALUES(60,'Think about a thunderstorm, they have a chaotic sound but when they are over everything is clean, fresh and beautiful again.');
INSERT INTO bobQuotes VALUES(61,'The joy in life comes from doing your own thing.');
INSERT INTO bobQuotes VALUES(62,'Go outside and make friends with a tree.');
INSERT INTO bobQuotes VALUES(63,'Do a little, but don’t get greedy.');
INSERT INTO bobQuotes VALUES(64,'All you have to do is decide and then let the rest happen.');
INSERT INTO bobQuotes VALUES(65,'It will look like life is just exploding.');
INSERT INTO bobQuotes VALUES(66,'At this point we’re not concerned - we’ll worry about that later.');
INSERT INTO bobQuotes VALUES(67,'Just a tiny bit, we don’t need much today.');
INSERT INTO bobQuotes VALUES(68,'If you look into the clouds long enough, you’ll find what you’re looking for.');
INSERT INTO bobQuotes VALUES(69,'Too much will ruin the illusion.');
INSERT INTO bobQuotes VALUES(70,'You just have to find what works for you.');
INSERT INTO bobQuotes VALUES(71,'It’s a long way off, we don’t even know where it goes - but we don’t need to care.');
INSERT INTO bobQuotes VALUES(72,'It gets to feel good and you want to just keep doing it, but the key is restraint.');
INSERT INTO bobQuotes VALUES(73,'Once you get over the fear, you’ll be amazed at what you can do.');
INSERT INTO bobQuotes VALUES(74,'Of course you can do that. You can do anything.');
INSERT INTO bobQuotes VALUES(75,'Trees grow in every shape and size, just like people - and that’s what makes them fantastic.');
INSERT INTO bobQuotes VALUES(76,'If you have to do something over again, it doesn’t mean you’re bad, it just means you’re normal.');
INSERT INTO bobQuotes VALUES(77,'Let your imagination take you anywhere you want to go.');
INSERT INTO bobQuotes VALUES(78,'If you don’t think you can do this - you’re not realizing how simple it is.');
INSERT INTO bobQuotes VALUES(79,'Nothing in the world breeds success like success, even if you start with the smallest amount.');
INSERT INTO bobQuotes VALUES(80,'There’s no good or bad. There’s just what makes you happy.');
INSERT INTO bobQuotes VALUES(81,'It really doesn’t matter, we can always paint over it.');
INSERT INTO bobQuotes VALUES(82,'Anything that you can visualize in your mind, you can do.');
INSERT INTO bobQuotes VALUES(83,'Sometimes you can amaze yourself.');
INSERT INTO bobQuotes VALUES(84,'All you have to do is realize there are no boundaries here.');
INSERT INTO bobQuotes VALUES(85,'You can do anything in this life. As long as you believe you can.');
INSERT INTO bobQuotes VALUES(86,'Sometimes life has a funny sense of humor.');
INSERT INTO bobQuotes VALUES(87,'Once in awhile you need a little sorrow in your life.');
INSERT INTO bobQuotes VALUES(88,'Don’t be afraid to go out on a limb. That’s where the fruit is.');
INSERT INTO bobQuotes VALUES(89,'Spend some time talking with the trees.');
INSERT INTO bobQuotes VALUES(90,'No one has ever been hurt by having too many friends.');
INSERT INTO bobQuotes VALUES(91,'We don’t need to set the sky on fire, a little glow will do just fine.');
INSERT INTO bobQuotes VALUES(92,'I love every little bird and critter.');
INSERT INTO bobQuotes VALUES(93,'It can be scary to have this much power.');
INSERT INTO bobQuotes VALUES(94,'Everybody has their own ideas, and that’s the way it should be.');
INSERT INTO bobQuotes VALUES(95,'The only rule is that you should enjoy this.');
INSERT INTO bobQuotes VALUES(96,'Remember, you can do anything in your world that you want to.');
INSERT INTO bobQuotes VALUES(97,'All it takes is just a little change of perspective and you begin to see a whole new world.');
INSERT INTO bobQuotes VALUES(98,'Everyone is going to see things differently - and that’s the way it should be.');
INSERT INTO bobQuotes VALUES(99,'You can create beautiful things - but you have to see them in your mind first');
INSERT INTO bobQuotes VALUES(100,'Don’t be afraid to make these big decisions. Once you start, they sort of just make themselves.');
INSERT INTO bobQuotes VALUES(101,'With something so strong, a little bit can go a long way.');
INSERT INTO bobQuotes VALUES(102,'Think about a cloud. Just float around and be there.');
INSERT INTO bobQuotes VALUES(104,'You have to put some dark color in so your light color will show.');
INSERT INTO bobQuotes VALUES(105,'In life you need colors.');
INSERT INTO bobQuotes VALUES(106,'It’s a super day, so why not make a beautiful sky?');
INSERT INTO bobQuotes VALUES(107,'It’s beautiful - and we haven’t even done anything to it yet');
INSERT INTO bobQuotes VALUES(108,'Pretend you’re water. Just floating without any effort. Having a good day.');
INSERT INTO bobQuotes VALUES(109,'They say everything looks better with odd numbers of things. But sometimes I put even numbers - just to upset the critics.');
INSERT INTO bobQuotes VALUES(110,'When things happen - enjoy them. They’re little gifts.');
INSERT INTO bobQuotes VALUES(111,'Take your time. Speed will come later.');
INSERT INTO bobQuotes VALUES(112,'It’s amazing what you can do with a little love in your heart.');
INSERT INTO bobQuotes VALUES(113,'God gave you this gift of imagination. Use it.');
INSERT INTO bobQuotes VALUES(114,'You can do anything your heart can imagine.');
INSERT INTO bobQuotes VALUES(115,'With practice comes confidence.');
INSERT INTO bobQuotes VALUES(116,'If you don’t like it - change it. It’s your world.');
INSERT INTO bobQuotes VALUES(117,'There is immense joy in just watching - watching all the little creatures in nature.');
INSERT INTO bobQuotes VALUES(118,'That is when you can experience true joy, when you have no fear.');
INSERT INTO bobQuotes VALUES(119,'We don’t really know where this goes - and I’m not sure we really care.');
INSERT INTO bobQuotes VALUES(120,'Life is too short to be alone, too precious. Share it with a friend.');
INSERT INTO bobQuotes VALUES(122,'Dead trees are also a part of nature.');
INSERT INTO bobQuotes VALUES(123,'Sometimes you learn more from your mistakes than you do from your masterpieces.');
INSERT INTO bobQuotes VALUES(124,'You want your tree to have some character. Make it special.');
INSERT INTO bobQuotes VALUES(125,'The man who does the best job is the one who is happy at his job.');
INSERT INTO bobQuotes VALUES(126,'Everything’s not great in life, but we can still find beauty in it.');
INSERT INTO bobQuotes VALUES(127,'You’re the greatest thing that has ever been or ever will be. You’re special. You’re so very special.');
INSERT INTO bobQuotes VALUES(128,'There are no accidents. There are no mistakes.');
INSERT INTO bobQuotes VALUES(129,'There is no right or wrong - as long as it makes you happy and doesn’t hurt anyone.');
INSERT INTO bobQuotes VALUES(130,'Everyone needs a friend. Friends are the most valuable things in the world.');
INSERT INTO bobQuotes VALUES(131,'There are no mistakes. You can fix anything that happens.');
INSERT INTO bobQuotes VALUES(132,'That’s why I paint - because I can create the kind of world I want - and I can make this world as happy as I want it.');
INSERT INTO bobQuotes VALUES(133,'How do you make a round circle with a square knife? That’s your challenge for the day.');
INSERT INTO bobQuotes VALUES(134,'Just think about these things in your mind - then bring them into your world.');
CREATE TABLE IF NOT EXISTS "bovontoPitches" (
	id INTEGER NOT NULL, 
	pitch VARCHAR, 
	PRIMARY KEY (id)
);
INSERT INTO bovontoPitches VALUES(1,'Hello, weary traveller! May I slake your thirst with a frosty Bovonto?');
INSERT INTO bovontoPitches VALUES(2,'Ah! In this summer heat a Bovonto will keep you cool!');
INSERT INTO bovontoPitches VALUES(3,'Good poster! May I interest you in a Bovonto this day?');
INSERT INTO bovontoPitches VALUES(4,'The pleasure of a Bovonto is nontrivial! Please, enjoy!');
INSERT INTO bovontoPitches VALUES(5,'To delight in a Bovonto: a simple, gracious treat!');
INSERT INTO bovontoPitches VALUES(6,'It is much like a dip in the ocean, to sup the Bovonto liquid!');
INSERT INTO bovontoPitches VALUES(7,'At this time of day we all feel down. Why not a crisp Bovonto to life your spirits?');
INSERT INTO bovontoPitches VALUES(8,'As the seasons change, so do our desires. Only the craving of Bovonto is perennial!');
INSERT INTO bovontoPitches VALUES(9,'Find in your heart the thirst for Bovonto!');
INSERT INTO bovontoPitches VALUES(10,'Bovonto: a wet treat!');
INSERT INTO bovontoPitches VALUES(11,'Tears of joy from an angel drizzle off a cloud and land precisely in a sleek bottle. Bovonto is born!');
INSERT INTO bovontoPitches VALUES(12,'What a performance! Bravo, Bovonto!');
INSERT INTO bovontoPitches VALUES(13,'It is impossible to frown while swallowing Bovonto!');
INSERT INTO bovontoPitches VALUES(14,'The world is full of uncountable sorrows. Bovonto may not cure them all, but it cannot hurt to try!');
INSERT INTO bovontoPitches VALUES(15,'Gold is not always gold. Sometimes it is the deep purple hue of Bovonto!');
INSERT INTO bovontoPitches VALUES(16,'To drink a Bovonto: A blessing of Christ!');
INSERT INTO bovontoPitches VALUES(17,'For every liter of blood in your body, I recommend an ounce of delicious Bovonto!');
INSERT INTO bovontoPitches VALUES(18,'If Bovonto were currency, all seekers of refreshment would be rich!');
INSERT INTO bovontoPitches VALUES(19,'Please, do not shy away from your feelings. Find in Bovonto the strength to speak out!');
INSERT INTO bovontoPitches VALUES(20,'Soldiers die. Forests burn. Bovonto Refreshes!');
INSERT INTO bovontoPitches VALUES(21,'Bovonto has been tied to fewer urinary tract infections than any other grape cola. Please enjoy!');
INSERT INTO bovontoPitches VALUES(22,'Weep not for the lost. Drink Bovonto in their name!');
INSERT INTO bovontoPitches VALUES(23,'Leap for joy, bliss is here! Bovonto!');
INSERT INTO bovontoPitches VALUES(24,'Drink deep from the bottle, and your deepest wish will be granted: Bovonto.');
INSERT INTO bovontoPitches VALUES(25,'The rock of plenty, the rock of faith: Bovonto');
COMMIT;
