embedBovontoIcon = "https://imgur.com/8aCQlV5.png"
pitches = ["Hello, weary traveller! May I slake your thirst with a frosty Bovonto?",
"Ah! In this summer heat a Bovonto will keep you cool!",
"Good poster! May I interest you in a Bovonto this day?",
"The pleasure of a Bovonto is nontrivial! Please, enjoy!",
"To delight in a Bovonto: a simple, gracious treat!",
"It is much like a dip in the ocean, to sup the Bovonto liquid!",
"At this time of day we all feel down. Why not a crisp Bovonto to life your spirits?",
"As the seasons change, so do our desires. Only the craving of Bovonto is perennial!",
"Find in your heart the thirst for Bovonto!",
"Bovonto: a wet treat!",
"Tears of joy from an angel drizzle off a cloud and land precisely in a sleek bottle. Bovonto is born!",
"What a performance! Bravo, Bovonto!",
"It is impossible to frown while swallowing Bovonto!",
"The world is full of uncountable sorrows. Bovonto may not cure them all, but it cannot hurt to try!",
"Gold is not always gold. Sometimes it is the deep purple hue of Bovonto!",
"The 'Dastardly Case of the Mondays' can be solved by Detective Bovonto! Please, try one!",
"To drink a Bovonto: A blessing of Christ!",
"For every liter of blood in your body, I recommend an ounce of delicious Bovonto!",
"If Bovonto were currency, all seekers of refreshment would be rich!",
"Please, do not shy away from your feelings. Find in Bovonto the strength to speak out!",
"I am a machine! To spread Bovonto's gospel, my purpose! Would you indulge me?",
"Soldiers die. Forests burn. Bovonto Refreshes!",
"Bovonto has been tied to fewer urinary tract infections than any other grape cola. Please enjoy!",
"Weep not for the lost. Drink Bovonto in their name!"]

