apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yaml --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: butterbean
  name: butterbean
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: butterbean
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yaml --chart
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: butterbean
    spec:
      containers:
        - command:
            - python
            - butterbean.py
          env:
            - name: BOT_MOD_NAME
              valueFrom:
                secretKeyRef:
                  key: BOT_MOD_NAME
                  name: butterbean
            - name: GITHUB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITHUB_ACCESS_TOKEN
                  name: butterbean
            - name: GITHUB_REPO_NAME
              valueFrom:
                secretKeyRef:
                  key: GITHUB_REPO_NAME
                  name: butterbean
            - name: MOD_NAME
              valueFrom:
                secretKeyRef:
                  key: MOD_NAME
                  name: butterbean
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: butterbean
          image: tupperward/butterbean:latest
          imagePullPolicy: Always
          name: butterbean
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /app/db
              name: butterbean
      restartPolicy: Always
      volumes:
        - name: butterbean
          persistentVolumeClaim:
            claimName: butterbean
