apiVersion: v1
data:
  BOT_MOD_NAME: dGVjaG5vbWFuY2VyCg==
  GITHUB_ACCESS_TOKEN: Z2hwX1JIa3FSMml6VlhwYXlQQW9SSGZocHlQUGRGZTFoTjFHb2Jtdwo=
  GITHUB_REPO_NAME: dHVwcGVyd2FyZC9idXR0ZXJiZWFuCg==
  MOD_NAME: c2hlcmlmZgo=
  TOKEN: TkRZMk5qazFNRGMxTnpjMU1qVXdORE16LkdBV2FnOC5kWWRjWXlwaDI1VXRsSi05RFVOcWNHYXluUlFJYi0wOXNHUWJDYwo=
kind: Secret
metadata:
  labels:
    io.kompose.service: butterbean
  name: butterbean
